# Generated by Django 3.0.8 on 2020-08-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('news', models.TextField()),
            ],
        ),
    ]
