# Generated by Django 3.0.8 on 2020-08-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=150)),
                ('tuesday', models.CharField(max_length=150)),
                ('wednesday', models.CharField(max_length=150)),
                ('thursday', models.CharField(max_length=150)),
                ('friday', models.CharField(max_length=150)),
                ('saturday', models.CharField(max_length=150)),
                ('sunday', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.CharField(blank=True, max_length=150)),
                ('price2', models.CharField(blank=True, max_length=150)),
                ('price3', models.CharField(blank=True, max_length=150)),
                ('price4', models.CharField(blank=True, max_length=150)),
                ('price5', models.CharField(blank=True, max_length=150)),
                ('price6', models.CharField(blank=True, max_length=150)),
                ('price7', models.CharField(blank=True, max_length=150)),
                ('price8', models.CharField(blank=True, max_length=150)),
                ('price9', models.CharField(blank=True, max_length=150)),
                ('price10', models.CharField(blank=True, max_length=150)),
                ('price11', models.CharField(blank=True, max_length=150)),
                ('price12', models.CharField(blank=True, max_length=150)),
                ('price13', models.CharField(blank=True, max_length=150)),
                ('price14', models.CharField(blank=True, max_length=150)),
                ('price15', models.CharField(blank=True, max_length=150)),
                ('price16', models.CharField(blank=True, max_length=150)),
                ('price17', models.CharField(blank=True, max_length=150)),
                ('price18', models.CharField(blank=True, max_length=150)),
                ('price19', models.CharField(blank=True, max_length=150)),
                ('price20', models.CharField(blank=True, max_length=150)),
                ('price21', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
